repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: migrations/
        args: ["--max-line-length=90"]
        additional_dependencies: [flake8-docstrings, flake8-length]

