# Generated by Django 3.2.4 on 2021-06-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailymailing',
            options={'verbose_name': 'Ежедневная рассылка', 'verbose_name_plural': 'Ежедневные рассылки'},
        ),
        migrations.AddField(
            model_name='dailymailing',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Активна'),
        ),
    ]
