# Generated by Django 3.2.4 on 2021-06-19 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tgbot', '0003_telegramuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymailing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Адресат'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.CharField(max_length=50, verbose_name='ID чата с пользователем'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Системный пользователь'),
        ),
    ]
